[docker_swarm_manager]
tf-node000 ansible_host=192.168.0.230

[docker_swarm_worker]
tf-node001 ansible_host=192.168.0.231
tf-node002 ansible_host=192.168.0.232

[all:vars]
ansible_python_interpreter=/usr/bin/python3
